import { Target } from "serenity-js/lib/serenity-protractor";
export declare class TodoList {
    static enter_user_id: Target;
    static enter_password: Target;
    static click_on_continue: Target;
    static error_message_displayed_for_login: Target;
    static clicl_on_register: Target;
    static enter_title_to_register: Target;
    static enter_firstName_to_register: Target;
    static enter_lastName_to_register: Target;
    static enter_date_to_register: Target;
    static enter_month_to_register: Target;
    static enter_year_to_register: Target;
    static enter_postCode_to_register: Target;
    static select_accountType_to_register: Target;
    static enter_sortCode_to_register: Target;
    static enter_accountNumber_to_register: Target;
    static click_on_continue_to_register: Target;
    static error_message_for_registration: Target;
    static credit_card_number: Target;
    static reference_loan_number: Target;
    static mortgage_number: Target;
    static Log_on_page_title: Target;
    static user_id: Target;
    static preferred_password: Target;
    static confirm_password: Target;
    static email_id: Target;
    static terms_and_conditions: Target;
    static security_reasons_text: Target;
    static submit_log_on_form: Target;
}
